input {
  file {
    path => "/app/logs/app-json.log"
    start_position => "beginning"
    codec => "json"
    type => "spring-boot-logs"
  }
}

filter {
  if [type] == "spring-boot-logs" {
    date {
      match => [ "@timestamp", "ISO8601" ]
      target => "@timestamp"
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "chatboot-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
