name: chatbootrad

include:
  - docker/services/qdrant.yml
  - docker/services/cheshire-cat.yml
  - docker/services/mongodb.yml
  - docker/services/frontend.yml
  - docker/services/backend.yml
  - docker/services/keycloak-db.yml
  - docker/services/keycloak.yml
  - docker/services/elk.yml

networks:
  cbr_network:
    driver: bridge
