spring.application.name=ChatBoot
server.port=8082
springdoc.swagger-ui.enabled=true

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://admin:changeme@mongodb:27017/chatboot?authSource=admin
spring.data.mongodb.database=chatboot
