FROM maven:3.9.6-eclipse-temurin-21
WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY . .

EXPOSE 8082
ENTRYPOINT ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments='-Dspring.devtools.restart.enabled=true'", "-Dspring-boot.run.fork=false"]
