services:
  backend:
    build:
      context: ../../backend/ChatBoot
      dockerfile: Dockerfile.dev
    container_name: cbr_backend
    restart: unless-stopped
    ports:
      - "8082:8082"
    depends_on:
      mongodb:
        condition: service_started
    volumes:
      - ../../backend/ChatBoot:/app
      - m2_cache:/root/.m2  # Volume dedicato per isolare Maven
    environment:
      - SERVER_PORT=8082
      - SPRING_DATA_MONGODB_URI=mongodb://admin:changeme@mongodb:27017/chatboot?authSource=admin
      - SPRING_DATA_MONGODB_DATABASE=chatboot
      - JWT_ISSUER_URI=http://localhost:8888/realms/ChatBot
      - JWT_JWK_SET_URI=http://keycloak:8080/realms/ChatBot/protocol/openid-connect/certs
      - KC_TOKEN_URI=http://keycloak:8080/realms/ChatBot/protocol/openid-connect/token
      - KC_CLIENT_ID=chatbot-backend
      - KC_CLIENT_SECRET=chatbot-backend-secret-12345
      # Configurazione Aggressiva per Hot Reload
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_RESTART_POLL_INTERVAL=2000
      - SPRING_DEVTOOLS_RESTART_QUIET_PERIOD=1000
      - SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING=true
    networks:
      - cbr_network

volumes:
  m2_cache:
