services:
  mongodb:
    image: mongo:7
    container_name: cbr_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ../volume/cbr_storage/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=changeme
    networks:
      - cbr_network

  mongo-gui:
    image: ugleiton/mongo-gui
    container_name: cbr_mongo_gui
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "4321:4321"
    environment:
      - MONGO_URL=mongodb://admin:changeme@mongodb:27017/
    networks:
      - cbr_network
