services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: cbr_qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - ../volume/cbr_storage/qdrant:/qdrant/storage
    networks:
      - cbr_network
    healthcheck:
      test: ["CMD", "bash", "-c", ": < /dev/tcp/localhost/6333"]
      interval: 10s
      timeout: 5s
      retries: 10        # era 5, alzato a 10
      start_period: 30s  # aspetta 30s prima di iniziare i controlli
